apiVersion: v1
kind: Pod
metadata:
  name: go-docker-1.example.com
  labels:
    app: helloworld-1
spec:
  containers:
  - name: k8s-demo
    image: 411953124370.dkr.ecr.eu-west-1.amazonaws.com/go-docker:v2
    ports:
    - name: go-port
      containerPort: 9000
  imagePullSecrets:
    - name: regcred

---
apiVersion: v1
kind: Pod
metadata:
  name: go-docker-2.example.com
  labels:
    app: helloworld-2
spec:
  containers:
  - name: k8s-demo
    image: 411953124370.dkr.ecr.eu-west-1.amazonaws.com/go-docker:v1
    ports:
    - name: go-port
      containerPort: 9000
  imagePullSecrets:
    - name: regcred