apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: 411953124370.dkr.ecr.eu-west-1.amazonaws.com/go-docker
    ports:
    - name: go-port
      containerPort: 9000
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
              name: db-secret
              key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
              name: db-secret
              key: password
  imagePullSecrets:
    - name: regcred