apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: cm9vdGhlbGxvCg==  # correspond à echo "roothello"| base64
  password: cGFzc3dvcmRoZWxsbwo= # correspond à echo "passwordhello"| base64